### ISSUE TITLE
packages needed for build on fedora

### ISSUE THREAD

**Issue by jhjaggars** [iphands/randy#1]
`glib-devel glib2-devel cairo-devel gdk-pixbuf2-devel pango-devel atk-devel cairo-gobject-devel gtk3-devel`

**Comment by mwcz** [comment]
I also needed `lm_sensors-devel`

**Comment by wwalker** [comment]
Thank you!.  This fixed the build for me on Fedora 32.

**Comment by iphands** [comment]
Closing this in favor of packaging: https://bugzilla.redhat.com/show_bug.cgi?id=1908929
Its still linked to from the readme though
