### ISSUE TITLE
Support putting at least some widgets side-by-side

### ISSUE THREAD

**Issue by ssokolow** [iphands/randy#27]
I decided to explore Randy as a replacement for Conky after upgrading to some new hard drives and a new Kubuntu LTS, but I realized that it doesn't seem to support putting multiple pieces of information on the same line.

Here's the layout I'm trying to make a viably compact replacement for:

![Screenshot_20210428_111835](https://user-images.githubusercontent.com/46915/116429401-62d82e80-a835-11eb-8580-2aa04e178d8e.png)

**Comment by iphands** [comment]
Love it. Time is tiiiight these days. New job, but I will look into this next time Im working on Randy.
Thanks!

**Comment by iphands** [comment]
Fixed on `main`
![1664477866](https://user-images.githubusercontent.com/129737/193118973-4abd508a-613f-444c-a080-b3a1e94c4066.jpg)
